version: '3.4'

services:

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    

  backend:
    container_name: fastapi-backend
    restart: always
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres@postgres/crm
    volumes:
      - ./backend/app:/code/app
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    container_name: next-frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - mynetwork
    volumes:
      - ./frontend:/usr/src/app
      - ignore:/src/app/node_modules/
    depends_on:
      - backend

volumes:
  db-data:
  ignore:
networks:
  mynetwork: